--CREANDO TABLA DE CLIENTES
CREATE SEQUENCE CLIENTES_SEQ START WITH 1;
ALTER SEQUENCE CLIENTES_SEQ NOCACHE;
CREATE TABLE CLIENTES(
    IDCLIENTE   INT DEFAULT CLIENTES_SEQ.NextVal NOT NULL,
    NOMBRE      VARCHAR2(80),
    APELLIDO    VARCHAR2(80),
    TELEFONO    VARCHAR2(8),
    EMAIL       VARCHAR2(30),
    DIRECCION   VARCHAR2(150),
    CONSTRAINT CLIENTES_PK PRIMARY KEY(IDCLIENTE)
);
COMMIT;

--INSERT INTO CLIENTES (IDCLIENTE,NOMBRE,APELLIDO,TELEFONO,EMAIL,DIRECCION) values (CLIENTES_SEQ.NextVal,?,?,?,?,?)
--SELECT IDCLIENTE, NOMBRE, APELLIDO, TELEFONO, EMAIL, DIRECCION FROM CLIENTES ORDER BY IDCLIENTE;

--CREANDO TABLA DE USUARIOS
CREATE SEQUENCE USUARIOS_SEQ START WITH 1;
ALTER SEQUENCE USUARIOS_SEQ NOCACHE;
CREATE TABLE USUARIOS
(
    IDUSER      INT DEFAULT USUARIOS_SEQ.NextVal NOT NULL,
    USERNAME    VARCHAR2(20),
    PASSWORD    VARCHAR2(25),
    NOMBRE      VARCHAR(80),
    CONSTRAINT USUARIOS_PK PRIMARY KEY(IDUSER)
);
COMMIT;

--INSERT INTO USUARIOS (IDUSER, USERNAME, PASSWORD, NOMBRE) VALUES(USUARIOS_SEQ.NextVal, 'jmeraz','123','Josue Meraz');

--CREANDO TABLA DE LIBROS
CREATE SEQUENCE LIBROS_SEQ START WITH 1;
ALTER SEQUENCE LIBROS_SEQ NOCACHE;
CREATE TABLE LIBROS(
    IDLIBRO     INT DEFAULT LIBROS_SEQ.NextVal NOT NULL,
    TITULO      VARCHAR2(80),
    EDITORIAL   VARCHAR2(80),
    AUTOR       VARCHAR2(80),
    IDIOMA      VARCHAR2(80),
    IMAGEN      VARCHAR2(150),
    YEAR        NUMBER(4),
    CONSTRAINT LIBROS_PK PRIMARY KEY(IDLIBRO)
);
COMMIT;

--CREANDO TABLA DE PRESTAMOS
CREATE SEQUENCE PRESTAMOS_SEQ START WITH 1;
ALTER SEQUENCE PRESTAMOS_SEQ NOCACHE;
CREATE TABLE PRESTAMOS(
    IDPRESTAMO      INT DEFAULT PRESTAMOS_SEQ.NextVal NOT NULL,
    IDCLIENTE       INT,
    IDLIBRO         INT,
    FECHAPRESTAMO   DATE,
    ACTIVO          CHAR(1),
    CONSTRAINT PRESTAMOS_PK PRIMARY KEY(IDPRESTAMO)
);

ALTER TABLE PRESTAMOS ADD CONSTRAINT FK_LIBRO FOREIGN KEY (IDLIBRO) REFERENCES LIBROS(IDLIBRO);
ALTER TABLE PRESTAMOS ADD CONSTRAINT FK_CLIENTE FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTES(IDCLIENTE);
COMMIT;

--CREANDO TABLA DE DEVULUCIONES
CREATE SEQUENCE DEVOLUCION_SEQ START WITH 1;
ALTER SEQUENCE DEVOLUCION_SEQ NOCACHE;
CREATE TABLE DEVOLUCION(
    IDDEVOLUCION        INT DEFAULT DEVOLUCION_SEQ.NextVal NOT NULL,
    IDPRESTAMO          INT,
    FECHADEVOLUCION     DATE
    CONSTRAINT DEVOLUCION_PK PRIMARY KEY(IDDEVOLUCION)
);
ALTER TABLE DEVOLUCION ADD CONSTRAINT FK_PRESTAMO FOREIGN KEY (IDPRESTAMO) REFERENCES PRESTAMOS(IDPRESTAMO);

COMMIT;










