/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package domain;

import Data.Conexion;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author henry
 */
public class PanelPendientesDevolver extends javax.swing.JPanel {

    Conexion con = new Conexion();

    /**
     * Creates new form PanelPendientesDevolver
     */
    public PanelPendientesDevolver() {
        initComponents();
        LoadData();
    }

    DefaultTableModel model;

    private void LoadData() {
        model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

        };
        try {
            con.conectar();
            String query = "SELECT t0.idprestamo, t0.fechaprestamo, t1.nombre,t1.apellido, t2.titulo, t2.autor, t0.activo FROM PRESTAMOS T0 INNER JOIN CLIENTES T1 ON t0.idcliente=t1.idcliente INNER JOIN libros T2 ON t0.idlibro=t2.idlibro WHERE t0.activo='Y'";
            model.setColumnIdentifiers(new Object[]{"ID", "FECHA", "CLIENTE", "LIBRO"});
            PreparedStatement psmt = Conexion.con.prepareStatement(query);
            ResultSet resp = psmt.executeQuery();
            while (resp.next()) {
                model.addRow(new Object[]{resp.getInt(1), resp.getString(2), resp.getString(3) + " " + resp.getString(4), resp.getString(5)});
            }
            jTable1.setModel(model);

        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
        con.desconexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelpendiente = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setColumnSelectionAllowed(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Pendiente2.png"))); // NOI18N
        jLabel1.setText("Pendientes Devolver");
        jLabel1.setPreferredSize(new java.awt.Dimension(180, 30));

        javax.swing.GroupLayout panelpendienteLayout = new javax.swing.GroupLayout(panelpendiente);
        panelpendiente.setLayout(panelpendienteLayout);
        panelpendienteLayout.setHorizontalGroup(
            panelpendienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpendienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelpendienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(panelpendienteLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 598, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelpendienteLayout.setVerticalGroup(
            panelpendienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpendienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelpendiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelpendiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getClickCount() == 2) {
            int filaseleccionada = jTable1.getSelectedRow();

            PanelDevolucion addcliente = new PanelDevolucion();
            addcliente.setSize(1000, 600);//tama;o
            addcliente.setLocation(0, 0);//posicion

            panelpendiente.removeAll();
            panelpendiente.add(addcliente, BorderLayout.CENTER);
            panelpendiente.revalidate();
            panelpendiente.repaint();
            
            PanelDevolucion.txtNumeroRegistro.setText(jTable1.getValueAt(filaseleccionada, 0).toString());
            PanelDevolucion.txtNumeroRegistro.setBackground(Color.red);
            PanelDevolucion.txtNumeroRegistro.setForeground(Color.white);
        }
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panelpendiente;
    // End of variables declaration//GEN-END:variables
}
